# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: legmr
  joint_model_group_pose: startmr
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_shoulder_fl
    - joint_elbow_fl
    - joint_wrist_fl
    - joint_end_fl
    - joint_shoulder_fr
    - joint_elbow_fr
    - joint_wrist_fr
    - joint_end_fr
    - joint_shoulder_ml
    - joint_elbow_ml
    - joint_wrist_ml
    - joint_end_ml
    - joint_shoulder_mr
    - joint_elbow_mr
    - joint_wrist_mr
    - joint_end_mr
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []